!include https://raw.githubusercontent.com/Bunnings-Engineering/plantuml.theme/main/theme/theme-colours.puml
!$theme = "BunningsSequence" 

<style>
root {   
}
</style>


skinparam {
    DefaultTextAlignment center
    Shadowing true
}

skinparam SequenceArrow {
    Color Black
    Bordercolor Black
}

skinparam actorStyle awesome
skinparam SequenceActor {
    BackgroundColor $BBeige
    BorderColor $BGreen
}

skinparam Note {
    BorderColor $BRed
    BackgroundColor $BBeige
}

skinparam SequenceParticipant {
    BackgroundColor $BGreen
    FontColor White
    BorderColor $BGreen
}

skinparam SequenceGroup {
    BackgroundColor $BBeige
}

skinparam SequenceLifeLine {
    BackgroundColor $BBeige
    BorderColor black
}

skinparam database {
    BackgroundColor $BGreen25
    BorderColor $BGreen
}

skinparam BoxPadding 5
skinparam ParticipantPadding 5
